# Introduction {#intro}

L’objectif de ce cours est de proposer une introduction à la science des données et aux principes de bases de l'apprentissage automatique supervisé. L'approche adoptée privilégie les exemples, et les notions étudiées seront systématiquement appliquées de manière concrète dans des travaux pratiques notés. 

Les exemples s'appuient sur des données simulées réparties en plusieurs catégories selon des lois spécifiques à chaque catégorie, mais aussi et surtout sur des données réelles. Dans les exemples réels, nous tenterons de prédire la survie des passagers lors du naufrage du Titanic, ou le diagnostic du cancer du sein à partir de mesures biologiques. Nous nous intéresserons à la reconnaissance automatique de caractères manuscrits et un défi final portera sur l'analyse d'opinion à partir de texte écrits.

Des connaissances élémentaires en calcul des probabilités et en théorie de l'information sont nécessaires pour aborder le cours. Après une introduction aux lois multidimensionnelles, notamment gaussiennes, le cours abordera les principes de la théorie de la décision et la minimisation de fonctions de perte en apprentissage supervisé. Ensuite, il appliquera cette théorie à l'intelligence artificielle prédictive et en particulier aux réseaux de neurones multicouches. Les travaux pratiques se feront en langage R, présenté lors du premier cours. Chaque élève sera amené à programmer plusieurs intelligences artificielles lors des travaux pratiques et à répondre à un défi d'analyse prédictive. Des connaissances de base en programmation et la motivation pour apprendre de nouvelles matières seront très utiles pour arriver au bout du défi.

Le contenu du cours est le suivant

* Introduction au langage R. 
* Lois de probabilités multidimensionnelles. 
* Théorie de la décision. 
* Apprentissage supervisé. Réseaux de neurones.


#### CONTRÔLE CONTINU :

Type d'évaluation : Contrôle continu en travaux dirigés et en travaux pratiques. Présence obligatoire notée.

#### SESSION NORMALE :

Type d'examen : Un examen écrit. L'examen portera notamment sur les définitions données en cours d'amphi et sur la manipulation de R. 

Durée : 2h00.
Documents autorisés : aucun
Documents interdits  : tous documents
Matériel : aucun